### ISSUE TITLE
Intermittent crashes in ios during App launch

### ISSUE THREAD

**Issue by mwang-incomm** [newrelic/newrelic-capacitor-plugin#106]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We're seeing some crashes in ios intermittently, its hard to reproduce, but when I try to debug it, I would often see an unhandled exception coming from this line of code 
let headersDict = NewRelic.generateDistributedTracingHeaders()

Any ideas why this might be happening? 

![image](https://github.com/user-attachments/assets/eacc4b81-4be0-40c7-b8f0-9ab72d2dd472)

## Steps to Reproduce

Launch the app in the simulator or on the phone
App crashes

## Expected Behavior

App should not crash

## Relevant Logs / Console output

Date/Time:           2024-10-15 16:24:40.8917 -0600
Launch Time:         2024-10-15 16:24:40.1277 -0600
OS Version:          iPhone OS 17.7 (21H16)
Release Type:        User
Baseband Version:    4.70.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: App [4649]

Triggered by Thread:  7

Application Specific Information:
abort() called

Last Exception Backtrace:
0   CoreFoundation                	       0x1a4cd4f20 __exceptionPreprocess + 164
1   libobjc.A.dylib               	       0x19cb7f2b8 objc_exception_throw + 60
2   Foundation                    	       0x1a3b1d1b8 -[_NSJSONWriter init] + 0
3   NewRelic                      	       0x1055708f4 0x1054fc000 + 477428
4   NewRelic                      	       0x105516978 0x1054fc000 + 108920
5   ...elicNewrelicCapacitorPlugin	       0x1046dd360 NewRelicCapacitorPluginPlugin.generateDistributedTracingHeaders(_:) + 104
6   ...elicNewrelicCapacitorPlugin	       0x1046dd60c @objc NewRelicCapacitorPluginPlugin.generateDistributedTracingHeaders(_:) + 52
7   Capacitor                     	       0x103da8a24 closure #2 in CapacitorBridge.handleJSCall(call:) + 856
8   Capacitor                     	       0x103da9418 thunk for @escaping @callee_guaranteed @Sendable () -> () + 48
9   libdispatch.dylib             	       0x1acb7d13c _dispatch_call_block_and_release + 32
10  libdispatch.dylib             	       0x1acb7edd4 _dispatch_client_callout + 20
11  libdispatch.dylib             	       0x1acb86400 _dispatch_lane_serial_drain + 748
12  libdispatch.dylib             	       0x1acb86f30 _dispatch_lane_invoke + 380
13  libdispatch.dylib             	       0x1acb91cb4 _dispatch_root_queue_drain_deferred_wlh + 288
14  libdispatch.dylib             	       0x1acb91528 _dispatch_workloop_worker_thread + 404
15  libsystem_pthread.dylib       	       0x20172c934 _pthread_wqthread + 288
16  libsystem_pthread.dylib       	       0x2017290cc start_wqthread + 8

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_malloc.dylib        	       0x1b4e75734 tiny_free_no_lock + 1720
1   libsystem_malloc.dylib        	       0x1b4e74c70 free_tiny + 496
2   libobjc.A.dylib               	       0x19cb8ea2c method_list_t::sortBySELAddress() + 356
3   libobjc.A.dylib               	       0x19cb8e36c fixupMethodList(method_list_t*, bool, bool) + 548
4   libobjc.A.dylib               	       0x19cb7827c prepareMethodLists(objc_class*, method_list_t**, int, bool, bool, char const*) + 228

## Your Environment

Angular 18.x
Capacitor 6.x
Capacitor Newrelic plugin 1.5.2

**Comment by mwang-incomm** [comment]
I am not sure if this is related, but just thought that I add that our APP loads translations from the device and that may delay the bootstrapping of the angular module. I am not sure if the plugin is dependent on the angular module being bootstrapped at the time of newrelic initialization or not but I have noticed that if I force our APP to load without the translations then the crash seems to go away.

**Comment by ndesai-newrelic** [comment]
@mwang-incomm is it possible to provide sample app?

**Comment by mwang-incomm** [comment]
yea, I'll try to create one

**Comment by mwang-incomm** [comment]
Can you try it with this repo here? https://github.com/mwang-incomm/my-angular-ionic
I think it only crashes on your phone. The error is intermittent in the simulator.

**Comment by ndesai-newrelic** [comment]
@mwang-incomm you need to start the agent first before making any http call, I will push my changes to your repo which fixes your issue.

**Comment by mwang-incomm** [comment]
@ndesai-newrelic Thank you! I think that did it. I don't see the crash anymore

**Comment by jltxwesley** [comment]
Hey @ndesai-newrelic, is there a way to disable the plugin locally? e.g. I don't want NewRelic to be run in the iOS emulator.
