### ISSUE TITLE
error on web

### ISSUE THREAD

**Issue by 24jr** [newrelic/newrelic-capacitor-plugin#25]
I mainly need the apps for this so its not ruining my app but if im on web devloping i get infinite error 
<img width="363" alt="Screen Shot 2023-03-15 at 11 42 05 AM" src="https://user-images.githubusercontent.com/34662182/225363494-66b9c11c-121f-40a9-9dfa-9e4454b640a2.png">

I have `import { NewRelicCapacitorPlugin } from '@newrelic/newrelic-capacitor-plugin';` imported on page but only used inside of `if(platform !== 'web'){...` to be clear

**Comment by ndesai-newrelic** [comment]
the plugin is not supported for web, you should use newrelic browser agent for web.

**Comment by 24jr** [comment]
@ndesai-newrelic I dont want anything for web just for this error not to show up. I only use web for developing and some admin stuff so dont need analytics. I dont want any New Relic stuff called while in web but the import alone causes this I believe even if func only called while in app

**Comment by baluworks** [comment]
@ndesai-newrelic   I have tried this also. but still not working. getting same error mentioned above.

**Comment by 24jr** [comment]
Ya i am using for Capacitor.getPlatform(); if not web btw

**Comment by baluworks** [comment]
@24jr .with this Capacitor.getplatform() are you able to run  in web?  can you pl provide more details  where are you using this Capacitor.getPlatform()

**Comment by kthai-nr** [comment]
@24jr @baluworks We've pushed out a [new release](https://www.npmjs.com/package/@newrelic/newrelic-capacitor-plugin/v/1.1.1) with non-functional implementations for web, which should fix the issue. Feel free to re-open this issue if you run into any more problems or questions.
