### ISSUE TITLE
Console.log behaviour

### ISSUE THREAD

**Issue by mvaljento** [newrelic/newrelic-capacitor-plugin#37]
Does the plugin by design change the way the console.log messages are displayed even if the plugin is not activated in the Angular code? Before the plugin was installed, I could easily debug the console log because it would show the source file correctly. Now all log messages seem to originate from the index.js.

If this is the cause of the plugin, I would suggest a configuration option to bypass this mechanism in the development environment.

**Comment by kthai-nr** [comment]
Hello, appreciate the suggestion. We'll take a look at this problem and try to make a better debugging experience. As for a workaround for Chrome DevTools, you can go to sources and find `node_modules/@newrelic/newrelic-capacitor-plugin` and add `index.js` to the ignore list. You should be able to see your source files after that.

**Comment by mvaljento** [comment]
Thanks for the advice, that fixed the source files issue. There are still other issues though, like not being able to drill down to logged objects, but hopefully the debugging experience will be improved in the future. Good luck!
