### ISSUE TITLE
Dependency issues on installation, with capacitor 5.x

### ISSUE THREAD

**Issue by RaduMirceaAndrei** [newrelic/newrelic-capacitor-plugin#40]
❯ npm install @newrelic/newrelic-capacitor-plugin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: yaroomsMobile@0.0.1
npm ERR! Found: @capacitor/core@5.0.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"5.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^4.0.0" from @newrelic/newrelic-capacitor-plugin@1.1.1
npm ERR! node_modules/@newrelic/newrelic-capacitor-plugin
npm ERR!   @newrelic/newrelic-capacitor-plugin@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/mircea/.npm/_logs/2023-05-17T11_12_54_464Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mircea/.npm/_logs/2023-05-17T11_12_54_464Z-debug-0.log

**Comment by kthai-nr** [comment]
@RaduMirceaAndrei Hello, appreciate the notice. You can resolve this by running with `npm install @newrelic/newrelic-capacitor-plugin --legacy-peer-deps`. We will update the plugin on our end to the latest versions in our next release, which should fix the problem.

**Comment by kthai-nr** [comment]
After taking a deeper look, there will be some compatibility issues with capacitor v5 due to Android being on Android Gradle Plugin 8. We will update our native android agent for AGP 8 compatibility in the coming weeks and will update this plugin when it is available.

**Comment by RaduMirceaAndrei** [comment]
@kthai-nr Hi. I appreciate the quick response and will keep an eye out for the next release. Thank you.

**Comment by therhenalsdev** [comment]
@kennyt276 Hi, Android agent v7 with support for AGP v8 has already been released

**Comment by ndesai-newrelic** [comment]
@therhenalsdev @RaduMirceaAndrei  Capacitor 5.0 support is released now. please let us know if you are facing any issue with latest release.

**Comment by ndesai-newrelic** [comment]
@therhenalsdev it is 1.3.0
