### ISSUE TITLE
Add Support for Browser Web

### ISSUE THREAD

**Issue by vanpyrzericj** [newrelic/newrelic-capacitor-plugin#41]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

With the current setup, we have to manually add the (very long) browser js tag to our root page (for example, in Vue3, the index.html page). If our app is also using capacitor, we now have to set a flag to determine whether or not to use the browser lib, or the capacitor/native package. This also adds more bloat to our apps.

## Desired Behavior

Given that all the methods are already set up and integrated with the native SDKs, additional support to add the browser-based tracking would be ideal. This way we can use the same methods, and depending on the runtime (is `IsPlatform`), they get shipped to the right place.

## Possible Solution

N/A

## Additional context

Sentry, Bugsnag & Segment all support hybrid (web and native) approaches using a single interface, for capacitor projects.

**Comment by ndesai-newrelic** [comment]
@vanpyrzericj we already have our browser agent for this.
