### ISSUE TITLE
infinite function calls GetAgentConfiguration

### ISSUE THREAD

**Issue by yussefbens** [newrelic/newrelic-capacitor-plugin#54]
when I'm running newrelic plugin on android, I get this infinite function calls to GetAgentConfiguration like this: 
<img width="876" alt="Screenshot 2023-09-25 at 18 11 35" src="https://github.com/newrelic/newrelic-capacitor-plugin/assets/11192475/c08d9d26-9277-43b8-913f-e1cbe160f589">
I face this issue when I navigate to fourth tab not when I'm opening the app first
and I only call NewRelicCapacitorPlugin.start({appKey:appToken}); once in app.component.ts

**Comment by ndesai-newrelic** [comment]
@yussefbens can you share your code where you are seeing this infinite calls?

**Comment by ndesai-newrelic** [comment]
@yussefbens can you check issue in current release?
