### ISSUE TITLE
Add support for noticeNetworkFailure

### ISSUE THREAD

**Issue by Toxiapo** [newrelic/newrelic-capacitor-plugin#65]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

I have noticed that we have the `noticeHttpTransaction` included in this plugin, however, [noticeNetworkFailure](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/network-request-failures/) was not. I was wondering if there's a plan to add that, or was this deliberately left out?

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

I can manually track failed network requests from my Capacitor app.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution
N/A

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

For the Capacitor app, most of the networks will happen on the Javascript side so I don't think we can use the example code from Android/iOS.

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Toxiapo** [comment]
Hi, @ndesai-newrelic. I was concerned that they may be tracked differently in the dashboard since there's a specific method for errors on android/ios, but if they are the same for Capacitor, I can definitely use it.

**Comment by ndesai-newrelic** [comment]
@Toxiapo  if you want to capture this kind of error we will add this method.
<img width="1130" alt="Screenshot 2023-10-26 at 12 47 33 PM" src="https://github.com/newrelic/newrelic-capacitor-plugin/assets/89222514/1f9a87fc-9871-44ed-a5f5-847e97eda1b2">

**Comment by Toxiapo** [comment]
Thanks @ndesai-newrelic, I think for now we will just use the `noticeHttpTransaction` method for our current release, but it would be really nice to have the network failure method for the future.
