### ISSUE TITLE
`networkRequestEnabled` doesn't work

### ISSUE THREAD

**Issue by kristojorg** [newrelic/newrelic-capacitor-plugin#66]
## Description

The New Relic Capacitor plugin does not record network requests made from within the webview layer, despite indicating it can automatically capture them in the docs.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

1. Install NewRelicCapacitorPlugin
2. Call `NewRelicCapacitorPlugin.start({appKey:appToken, agentConfiguration:agentConfig})` with `networkRequestEnabled: true` in your `agentConfig`
3. Make `fetch` requests in your capacitor webview
4. The fetch request will not appear in NewRelic 

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

The fetch request will be captured and tracked to New Relic automatically. 

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

Tested in browser environment, as well as iOS and Android.

**Comment by ndesai-newrelic** [comment]
@kristojorg we are not supporting fetch instrumentation yet, we will add it in future release.

**Comment by kristojorg** [comment]
@ndesai-newrelic I see. It would be great to remove options that don't work from the github docs, website and even typscript defs if possible. It's a little frustrating to spend hours trying to get something working that the docs say will work only to open an issue to find out it isn't implemented... 

Thank you!

**Comment by kristojorg** [comment]
Yes I totally understand that it may take time. Just would be nice to have the API and docs reflect what's actually working

**Comment by kristojorg** [comment]
Would y'all accept a PR to remove these nonfunctional values from the type definitions?

**Comment by ndesai-newrelic** [comment]
we accept PR for this repo

**Comment by kristojorg** [comment]
Woohoo! Glad this is being implemented : )
