### ISSUE TITLE
Plugin with id 'newrelic' not found.

### ISSUE THREAD

**Issue by hughknaus** [newrelic/newrelic-capacitor-plugin#71]
## Description & Steps to Reproduce

Following these steps: https://github.com/newrelic/newrelic-capacitor-plugin?tab=readme-ov-file#android-setup and those steps seem to have some overlap with some differences from https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-agent-gradle/#manual-install.  For one, I'm using Capacitor/Trapeze to build the Android project which works great with modifying `build.gradle`, `app/build.gradle`, and `AndroidManifest.xml`.  However, in Android Studio it has the error `Plugin with id 'newrelic' not found.` So it cannot be built.

I tried adding `import com.newrelic.agent.android.NewRelic;` to the MainActivity.java and adding an `onCreate(...)` with `NewRelic.withApplicationToken("<GENERATED_TOKEN>").start(this.getApplicationContext());` but issue remains.

## Expected Behavior

Expect that since I can build the Ionic/Angular app with Capacitor/Trapeze and generate the Android app that I would be able to build the app from within Android Studio.

## Relevant Logs / Console output

Android Studio output:
```
Build file '/Volumes/Storage/_projects/<MYPROJECTNAME>/android/app/build.gradle' line: 58

A problem occurred evaluating project ':app'.
> Plugin with id 'newrelic' not found.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
```

## Your Environment

Apple M2 Max, Sonoma 14.3
Ionic/Angular app building with Capacitor/Trapeze
Android Studio Giraffe | 2022.3.1 Patch 1
** Have not tried building iOS version yet

**Comment by ndesai-newrelic** [comment]
@hughknaus did you add newrelic classpath in your configuration?
<img width="945" alt="Screenshot 2024-01-30 at 11 59 14 AM" src="https://github.com/newrelic/newrelic-capacitor-plugin/assets/89222514/f96a9f3f-c206-41e8-a419-d55f3df8d8ce">

**Comment by hughknaus** [comment]
@ndesai-newrelic  I added this classpath, which does differ from your screenshot:
![Uploading Screenshot 2024-01-30 at 12.16.19 PM.png…]()

and it does not have the pointer to the `files(...)` I'll give that a shot.

**Comment by ndesai-newrelic** [comment]
@hughknaus no need to add files in classpath.

**Comment by ndesai-newrelic** [comment]
@hughknaus It appears that there might be a bug in the Trapeze installation process where the classpath is not added correctly. In order to address this, you can manually add the classpath while following the installation steps.

**Comment by hughknaus** [comment]
@ndesai-newrelic I figured it out... silly mistake.  I had a colon after `classpath` so it was showing up like this:

```
classpath: "com.newrelic.agent.android:agent-gradle-plugin:7.2.0"
```
After removing the colon in my Trapeze file then it worked like magic.  Sorry for taking your time.
