### ISSUE TITLE
Unexpected output from log when newrelic is installed

### ISSUE THREAD

**Issue by Toxiapo** [newrelic/newrelic-capacitor-plugin#77]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I realized ever since I installed this package to my codebase, I see strange behavior to my console.log function, and it's showing empty logs in the console at app start. 

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
Install @newrelic/newrelic-capacitor-plugin@1.3.5 in your capacitor app and start the app, it outputs empty logs `[]: [object Object]`

Also, when I run the following code 
```js
 console.log("log:",  { book: { title:'book1' });
```
it doesn't output the detail of the log, instead, it prints `[]: []: log: '[]: [object Object]'`

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
I expect the app runs without outputting any console logs that's not part of my debugging logs, and when calling `console.log` with array or object, it should display the full content.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

- Macbook Pro intel
- Tested in localhost browser

**Comment by ndesai-newrelic** [comment]
@Toxiapo we will check it from our side.

**Comment by Toxiapo** [comment]
Hi @ndesai-newrelic, thank you for looking into this. Any updates on this bug? Would love to hear if there's been any progress.

**Comment by ndesai-newrelic** [comment]
@Toxiapo we will fix this issue for next release.

**Comment by ndesai-newrelic** [comment]
@Toxiapo i fixed it and please check it.

**Comment by Toxiapo** [comment]
@ndesai-newrelic Thank you! I will give this a test ASAP
