### ISSUE TITLE
Override of fetch adding unwanted headers

### ISSUE THREAD

**Issue by LuisRizo** [newrelic/newrelic-capacitor-plugin#95]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
On import of the newrelic capacitor NPM package, the fetch method will be overwritten such that new headers (newrelic, traceparent, tracestate) are added to every network request. This is causing CORS issues for our API.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

We are getting CORS issues when hitting our APIs by simply importing this NPM package. This is due to the override in fetch adding three new headers to every network request as seen here: https://github.com/newrelic/newrelic-capacitor-plugin/blob/b1405c6b7a1886aa9225ef50d4c8f9aed15ab4e9/src/index.ts#L172-L174.

This was tested in version 1.3.7, but the code in the latest version is still showing the above code.

This is a problem because our APIs are rejecting these headers, as they are not part of our existing `Access-Control-Allow-Headers`. For context, we use newrelic in our NodeJS backend, native android and iOS apps, and web browser. We've never had to manually allow these headers and haven't seen docs requiring that to be changed in the servers. So I believe this is a bug.

I even tried disabling `networkRequestEnabled` in the config, but that didn't help. And after reviewing the source code realized there's no way to disable this with a config change.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
1. Install `@newrelic/newrelic-capacitor-plugin` in a Capacitor project
2. Run the plugin setup as indicated in https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ionic-capacitor/get-started/introduction-new-relic-ionic-capacitor/
3. Import the plugin in the root of your React project
4. Make a fetch API call to a server that has a set `Access-Control-Allow-Headers` that does not include `newrelic`, `traceparent`, or `tracestate`.
5. Run the app and trigger the Network request
6. Notice the error in the console, as well as the network failing due to CORS

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )
I expect the network requests going to any domain that is not newrelic, or the configured `collectorAddress`, to not have extra headers.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
![image](https://github.com/user-attachments/assets/7a34ffca-a784-49a3-84f4-c44a3ccb37c7)

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Reproducible in browser:
Browsers: Chrome 126.0.6478.127
Operating System: Mac M1 2020

Reproducible in Capacitor:
iOS: iPhone 15 Pro 17.4 Simulator

NPM:
@capacitor/core: 5.0.3
@newrelic/newrelic-capacitor-plugin: 1.3.7
react: 17.0.2

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
We currently use new relic in iOS, Android, and the Browser.
We use a `collectorAddress` (`beacon`) in the above environments using the New Relic SDK.

Using that same setting in Capacitor did not help with the above error. The network requests to other endpoints still included these headers in all the `fetch` requests done by the same React app.

We use `fetch` for the majority of our network calls, including login the user in, getting all the user data, etc... This makes our app not load at all when New Relic adds those headers that cause a CORS error on all the network calls.

Adding those headers to our APIs is an option, but I don't believe that to be the right solution and it would require changes across multiple repositories, so I would like to leave that as a last resort.

**Comment by ndesai-newrelic** [comment]
@LuisRizo We've implemented additional headers to enable DistributedTracing functionality. To date, we haven't received any reports of these headers causing Cross-Origin Resource Sharing (CORS) issues. However, to provide flexibility and address potential concerns, we're considering adding a configuration flag that would allow users to opt out of including these headers in network requests if needed.

**Comment by ndesai-newrelic** [comment]
We have Created Internal Ticket to fix this issue.

**Comment by ndesai-newrelic** [comment]
it is fixed in 1.5.1 and we added distibutedTracingEnabled Flag to disable the distributed Tracing.
