### ISSUE TITLE
Web implementation is broken in version 1.5.0

### ISSUE THREAD

**Issue by mwang-incomm** [newrelic/newrelic-capacitor-plugin#98]
When updated to use the version 1.5.0 plugin, the web site fails to load.

## Description

After updating to 1.5.0, the web site fails to load. In the console it displays a "attributes are empty" error.

## Steps to Reproduce

Create new Ionic app using angular 
Install version 1.5.0 of the newrelic-capacitor-plugin
Run the web site

## Expected Behavior

Web site should run and display

## Relevant Logs / Console output

I was not able to get the text version of the console output because the site is stuck in a endless loading loop. Here is a screenshot of the errors:
![image](https://github.com/user-attachments/assets/d347ec49-d18e-4682-a158-574fa6fa0424)

## Your Environment

I have reproduced this with windows as well as MacOs, so I don't think the environment matters.

## Additional context

N/A

**Comment by ndesai-newrelic** [comment]
@mwang-incomm we will check it.

**Comment by ndesai-newrelic** [comment]
@mwang-incomm added fix for this. we will release it soon

**Comment by ndesai-newrelic** [comment]
it is fixed in 1.5.1
